//! Property tests over generated source and generated bytecode.
//!
//! `SECURITY.md` puts "hand-crafted or corrupted bytecode should fail safely"
//! in scope. These assert that: whatever the compiler and the interpreter are
//! handed, they answer with a `VmError` or a clean halt, and never panic, abort,
//! or leave the heap in a state where a live root points at a reclaimed object.
//!
//! `SpawnActor` and `SpawnSupervisor` are deliberately left out of the
//! generator. Each one moves a child VM running arbitrary bytecode onto the
//! Tokio runtime, and a generated child that loops forever would keep spinning
//! after its case finished. The existing suites cover spawning directly.

use proptest::prelude::*;
use proptest::strategy::ValueTree;

use raft::vm::execution::{ExecutionContext, ExecutionState};
use raft::vm::heap::{Heap, HeapObject, NativeFunction};
use raft::vm::opcodes::OpCode;
use raft::vm::value::Value;
use raft::vm::VmError;
use raft::Compiler;

/// Enough steps to get well past any bounded program, and to spin a generated
/// backward jump many times, without running forever.
const STEP_BUDGET: usize = 500;

/// Addresses a generated program can plausibly reach.
const ADDRESS_SPACE: usize = 32;

fn identity_native(args: Vec<Value>) -> Result<Value, VmError> {
    Ok(args.into_iter().next().unwrap_or(Value::Null))
}

fn arbitrary_value() -> impl Strategy<Value = Value> {
    prop_oneof![
        any::<i32>().prop_map(Value::Integer),
        any::<f64>().prop_map(Value::Float),
        any::<bool>().prop_map(Value::Boolean),
        Just(Value::Null),
        // References to addresses that may or may not hold anything: the point
        // is that a bogus one is rejected rather than followed.
        (0..ADDRESS_SPACE).prop_map(Value::Reference),
    ]
}

fn arbitrary_name() -> impl Strategy<Value = String> {
    prop_oneof![
        Just("io".to_string()),
        Just("print".to_string()),
        Just("missing".to_string()),
        "[a-z]{1,4}".prop_map(|name| name),
    ]
}

fn arbitrary_opcode() -> impl Strategy<Value = OpCode> {
    prop_oneof![
        arbitrary_value().prop_map(OpCode::PushConst),
        (0usize..8).prop_map(OpCode::StoreVar),
        (0usize..8).prop_map(OpCode::LoadVar),
        arbitrary_name().prop_map(OpCode::LoadGlobal),
        arbitrary_name().prop_map(OpCode::GetExport),
        (0usize..4).prop_map(OpCode::MakeArray),
        Just(OpCode::Pop),
        Just(OpCode::Dup),
        Just(OpCode::Swap),
        Just(OpCode::Add),
        Just(OpCode::Sub),
        Just(OpCode::Mul),
        Just(OpCode::Div),
        Just(OpCode::Mod),
        Just(OpCode::Neg),
        Just(OpCode::Exp),
        Just(OpCode::ArrayGet),
        Just(OpCode::ArraySet),
        "[a-z ]{0,8}".prop_map(OpCode::MakeString),
        "[a-z ]{0,8}".prop_map(OpCode::PushString),
        Just(OpCode::StringConcat),
        prop::collection::vec(arbitrary_name(), 0..3).prop_map(OpCode::MakeModule),
        arbitrary_name().prop_map(OpCode::ModuleGet),
        arbitrary_name().prop_map(OpCode::ModuleSet),
        Just(OpCode::MakeNativeFunction(NativeFunction {
            name: "identity".to_string(),
            arity: 1,
            function: identity_native,
        })),
        (0usize..3).prop_map(OpCode::CallNative),
        (0usize..ADDRESS_SPACE).prop_map(OpCode::Jump),
        (0usize..ADDRESS_SPACE).prop_map(OpCode::JumpIfFalse),
        (0usize..ADDRESS_SPACE).prop_map(OpCode::Call),
        Just(OpCode::Return),
        Just(OpCode::SendMessage),
        Just(OpCode::ReceiveMessage),
        (0usize..3).prop_map(OpCode::SetStrategy),
        (0usize..ADDRESS_SPACE).prop_map(OpCode::RestartChild),
    ]
}

/// A short sequence of opcodes that does one meaningful thing.
///
/// Sampling opcodes one at a time almost never produces a sequence like "build
/// a one-element array, then read element 0 back out" -- four specific opcodes
/// landing in order is roughly a one-in-400,000 event, and reference-lifetime
/// bugs live in exactly those sequences. Generating whole fragments instead
/// puts the interesting shapes within reach: any two adjacent draws can form a
/// build/read pair.
fn fragment() -> impl Strategy<Value = Vec<OpCode>> {
    prop_oneof![
        // Build.
        "[a-z]{1,4}".prop_map(|text| vec![OpCode::MakeString(text)]),
        "[a-z]{1,4}".prop_map(|text| vec![OpCode::MakeString(text), OpCode::MakeArray(1)]),
        "[a-z]{1,4}".prop_map(|text| vec![
            OpCode::MakeString(text),
            OpCode::MakeString("second".to_string()),
            OpCode::MakeArray(2),
        ]),
        "[a-z]{1,4}".prop_map(|text| vec![
            OpCode::MakeString(text),
            OpCode::MakeModule(vec!["export".to_string()]),
        ]),
        // Read back out. These consume the container, which is where a
        // container holding the last reference to its child matters.
        Just(vec![OpCode::PushConst(Value::Integer(0)), OpCode::ArrayGet]),
        Just(vec![OpCode::PushConst(Value::Integer(1)), OpCode::ArrayGet]),
        Just(vec![OpCode::ModuleGet("export".to_string())]),
        Just(vec![OpCode::GetExport("print".to_string())]),
        // Overwrite.
        Just(vec![
            OpCode::PushConst(Value::Integer(0)),
            OpCode::PushConst(Value::Integer(9)),
            OpCode::ArraySet,
        ]),
        Just(vec![
            OpCode::PushConst(Value::Integer(9)),
            OpCode::ModuleSet("export".to_string()),
        ]),
        // Move between roots.
        (0usize..3).prop_map(|slot| vec![OpCode::StoreVar(slot)]),
        (0usize..3).prop_map(|slot| vec![OpCode::LoadVar(slot)]),
        Just(vec![OpCode::LoadGlobal("io".to_string())]),
        // Shuffle and discard.
        Just(vec![OpCode::Dup]),
        Just(vec![OpCode::Pop]),
        Just(vec![OpCode::Swap]),
        Just(vec![OpCode::StringConcat]),
    ]
}

fn fragment_program() -> impl Strategy<Value = Vec<OpCode>> {
    prop::collection::vec(fragment(), 1..7).prop_map(|fragments| fragments.concat())
}

fn arbitrary_program() -> impl Strategy<Value = Vec<OpCode>> {
    prop_oneof![
        // Unstructured: reaches decoding, bounds checks and type errors.
        prop::collection::vec(arbitrary_opcode(), 0..ADDRESS_SPACE),
        // Structured: reaches object lifetimes.
        fragment_program(),
    ]
}

/// Step until the program halts, fails, yields, or exhausts its budget.
fn drive(execution: &mut ExecutionContext, heap: &mut Heap) {
    for _ in 0..STEP_BUDGET {
        match execution.step(heap) {
            Ok(ExecutionState::Continue) => {}
            // Halted, blocked on a mailbox, or failed: all acceptable outcomes.
            Ok(ExecutionState::Halted) | Ok(ExecutionState::Yield(_)) | Err(_) => return,
        }
    }
}

/// Every heap address a root still holds, in stack, locals and globals order.
fn rooted_addresses(execution: &ExecutionContext) -> Vec<usize> {
    execution
        .stack
        .iter()
        .chain(execution.locals.values())
        .chain(execution.globals.values())
        .filter_map(|value| match value {
            Value::Reference(address) => Some(*address),
            _ => None,
        })
        .collect()
}

fn live_addresses(heap: &Heap) -> Vec<usize> {
    (0..ADDRESS_SPACE * 4)
        .filter(|address| heap.get(*address).is_some())
        .collect()
}

proptest! {
    #![proptest_config(ProptestConfig { cases: 256, ..ProptestConfig::default() })]

    /// The compiler answers, one way or the other, for any input at all.
    #[test]
    fn compiling_arbitrary_text_never_panics(source in ".{0,200}") {
        let _ = Compiler::compile(&source);
    }

    /// Same, over text built from the tokens the lexer actually recognizes,
    /// which reaches far deeper into the parser than random bytes do.
    #[test]
    fn compiling_arbitrary_token_soup_never_panics(
        tokens in prop::collection::vec(
            prop_oneof![
                Just("1".to_string()),
                Just("-2".to_string()),
                Just("3.5".to_string()),
                Just("true".to_string()),
                Just("\"text\"".to_string()),
                Just(".label".to_string()),
                Just("+".to_string()),
                Just("Jump".to_string()),
                Just("StoreVar".to_string()),
                Just("MakeModule".to_string()),
                Just("CallNative".to_string()),
                Just("io.print".to_string()),
                Just("#comment\n".to_string()),
                Just("\\".to_string()),
                Just("\"unterminated".to_string()),
            ],
            0..24,
        )
    ) {
        let _ = Compiler::compile(&tokens.join(" "));
    }

    /// Anything the compiler accepts, the interpreter must handle.
    #[test]
    fn running_anything_that_compiles_never_panics(source in ".{0,120}") {
        if let Ok(bytecode) = Compiler::compile(&source) {
            let mut execution = ExecutionContext::new(bytecode);
            let mut heap = Heap::new();
            drive(&mut execution, &mut heap);
        }
    }

    /// Hand-crafted bytecode -- the case SECURITY.md calls out -- must fail
    /// safely rather than panicking or running away.
    #[test]
    fn executing_arbitrary_bytecode_never_panics(program in arbitrary_program()) {
        let mut execution = ExecutionContext::new(program);
        let mut heap = Heap::new();
        drive(&mut execution, &mut heap);
    }

    /// Collection must never reclaim an object a root still points at.
    #[test]
    fn collection_never_reclaims_a_rooted_object(program in arbitrary_program()) {
        let mut execution = ExecutionContext::new(program);
        let mut heap = Heap::new();
        drive(&mut execution, &mut heap);

        heap.collect_garbage();

        for address in rooted_addresses(&execution) {
            prop_assert!(
                heap.get(address).is_some(),
                "address {address} is still held by a root but was collected",
            );
        }
    }

    /// Collection is a fixpoint: once it has run, running it again on an
    /// untouched heap must not reclaim anything further.
    #[test]
    fn collection_reaches_a_fixpoint(program in arbitrary_program()) {
        let mut execution = ExecutionContext::new(program);
        let mut heap = Heap::new();
        drive(&mut execution, &mut heap);

        heap.collect_garbage();
        let after_first = live_addresses(&heap);
        heap.collect_garbage();
        let after_second = live_addresses(&heap);

        prop_assert_eq!(
            after_first,
            after_second,
            "a second collection changed the live set",
        );
    }

    /// Every object a live container points at must itself be live, or the
    /// container holds a dangling address.
    #[test]
    fn live_containers_never_point_at_reclaimed_objects(program in arbitrary_program()) {
        let mut execution = ExecutionContext::new(program);
        let mut heap = Heap::new();
        drive(&mut execution, &mut heap);
        heap.collect_garbage();

        for address in live_addresses(&heap) {
            let children = match heap.get(address) {
                Some(object) => object.references(),
                None => continue,
            };
            for child in children {
                prop_assert!(
                    heap.get(child).is_some(),
                    "live object at {address} points at reclaimed object {child}",
                );
            }
        }
    }

    /// Message conversion answers for any heap value, including the malformed
    /// ones a generated program leaves behind.
    #[test]
    fn converting_any_value_to_a_message_never_panics(program in arbitrary_program()) {
        let mut execution = ExecutionContext::new(program);
        let mut heap = Heap::new();
        drive(&mut execution, &mut heap);

        for address in 0..ADDRESS_SPACE {
            let _ = heap.value_to_message(Value::Reference(address));
        }
    }
}

#[test]
fn the_generated_programs_actually_allocate() {
    // A guard on the generator itself: if it stopped producing programs that
    // touch the heap, the invariants above would pass vacuously.
    let mut runner = proptest::test_runner::TestRunner::deterministic();
    let strategy = arbitrary_program();

    let mut allocated = 0;
    for _ in 0..256 {
        let program = strategy
            .new_tree(&mut runner)
            .expect("generating a program should succeed")
            .current();
        let mut execution = ExecutionContext::new(program);
        let mut heap = Heap::new();
        drive(&mut execution, &mut heap);
        if heap.get(0).is_some() {
            allocated += 1;
        }
    }

    assert!(
        allocated > 10,
        "expected generated programs to allocate, only {allocated} of 256 did"
    );
}

#[test]
fn heap_objects_are_reachable_for_the_invariants_to_be_meaningful() {
    // Sanity: a container really does report its children, so
    // `live_containers_never_point_at_reclaimed_objects` is testing something.
    let mut heap = Heap::new();
    let child = heap.allocate(HeapObject::String("child".to_string(), 1));
    let parent = heap.allocate(HeapObject::Array(vec![Value::Reference(child)], 1));
    assert_eq!(
        heap.get(parent).expect("parent should exist").references(),
        vec![child]
    );
}
